# Generated by Django 3.0.1 on 2020-01-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanupload',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scanupload',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scanupload',
            name='upload_Main_Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
