# Generated by Django 3.0.1 on 2020-01-07 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200107_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanupload',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
