# Generated by Django 3.0.1 on 2020-01-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_scanupload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanupload',
            name='upload_Main_Img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
