# Generated by Django 3.0.1 on 2020-01-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200107_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanupload',
            name='visiname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
