# Generated by Django 3.0.1 on 2020-01-09 14:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_scanupload_visiname'),
    ]

    operations = [
        migrations.CreateModel(
            name='expectedvisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('no_of_visitors', models.CharField(blank=True, max_length=10, null=True)),
                ('expected_datetime_of_arrival', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('date', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
