# Generated by Django 3.0.1 on 2020-01-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_expectedvisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedvisitor',
            name='expected_datetime_of_arrival',
            field=models.DateTimeField(blank=True),
        ),
    ]
