# Generated by Django 3.0.1 on 2020-01-09 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_friendvisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedvisitor',
            name='user',
            field=models.ForeignKey(default='vijay', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='friendvisitor',
            name='user',
            field=models.ForeignKey(default='vijay', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
