# Generated by Django 3.0.1 on 2020-01-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_scanupload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanupload',
            name='status',
            field=models.CharField(blank=True, choices=[('allow', 'Allow'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
