# Generated by Django 3.0.1 on 2020-01-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200113_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanupload',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scanupload',
            name='status',
            field=models.BooleanField(blank=True, choices=[('allow', 'Allow'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
