# Generated by Django 3.0.1 on 2020-01-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20200113_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanupload',
            name='visiname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
