# Generated by Django 3.0.1 on 2020-01-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20200113_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanupload',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=50),
        ),
    ]
