# Generated by Django 3.0.1 on 2020-01-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20200113_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanupload',
            name='status',
            field=models.CharField(blank=True, choices=[('activated', 'Activated'), ('deactivated', 'Deactivated')], default='pending', max_length=50),
        ),
    ]
