# Generated by Django 3.0.1 on 2020-01-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20200113_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanupload',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
