# Generated by Django 3.0.1 on 2020-01-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20200115_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendvisitor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
