# Generated by Django 3.0.1 on 2020-01-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20200115_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='visiname',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
