# Generated by Django 3.0.1 on 2020-01-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20200115_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendvisitor',
            name='role',
            field=models.CharField(blank=True, default='friend', max_length=50, null=True),
        ),
    ]
